### PR TITLE
Removed async wrappers around sync methods and associated unit tests

### PR DESCRIPTION
**Pull request by eridleyj**

### CODE REVIEW

**Comment by ebergstedt** [comment]
Hello, thanks for your pull request

I realize now that the "FromByteArray" and "ToByteArray" would not need async, due to it being extremely fast.

But I think SaveToFile and FromFile could profit from being async, if we wrap the "File.WriteAllBytes(filePath, byteArray);" and "File.ReadAllBytes(filePath);" in their own async context.

What do you think?

**Comment by ebergstedt** [comment]
I have now removed the async on bytearray and implemented proper async on file read on the master.

**Comment by eridleyj** [comment]
Yes, using the naturally async FileStream methods is a good call. Note, though, that FileSream has a [constructor overload](https://msdn.microsoft.com/en-us/library/7db28s3c.aspx) which takes in a bool **useAsync**: 

> Specifies whether to use asynchronous I/O or synchronous I/O. However, note that the underlying operating system might not support asynchronous I/O, so when specifying true, the handle might be opened synchronously depending on the platform. When opened asynchronously, the BeginRead and BeginWrite methods perform better on large reads or writes, but they might be much slower for small reads or writes. If the application is designed to take advantage of asynchronous I/O, set the useAsync parameter to true. Using asynchronous I/O correctly can speed up applications by as much as a factor of 10, but using it without redesigning the application for asynchronous I/O can decrease performance by as much as a factor of 10.

A little more background on what exactly that flag does [here](http://writeasync.net/?p=2201).

**Comment by ebergstedt** [comment]
Yes, I have implemented it as such. I will not merge this request, since it's now redundant, but I can put you as a contributor in a Contributor heading. Would that be alright?

**Comment by ejohnsonTKTNET** [comment]
Ah, yes, I see in FromFileAsync you are using FileOptions.Asynchronous, which is what the constructor with the **useAsync** flag sets under the hood when used:

>public FileStream(String path, FileMode mode, FileAccess access, FileShare share, int bufferSize, bool useAsync)
    : this(path, mode, access, share, bufferSize, (useAsync ? FileOptions.Asynchronous : FileOptions.None), Path.GetFileName(path), false)
{
}

Good to know; thanks. You aren't using either overload in SaveToFileAsync, though, which is what I was looking at when I wrote my above comment:

> using (var fs = new FileStream(filePath, fileMode))

Contributor stuff sounds good. Thanks!

**Comment by eridleyj** [comment]
Ah, yes, I see in FromFileAsync you are using FileOptions.Asynchronous, which is what the constructor with the useAsync flag sets under the hood when used:

> public FileStream(String path, FileMode mode, FileAccess access, FileShare share, int bufferSize, bool useAsync)
> : this(path, mode, access, share, bufferSize, (useAsync ? FileOptions.Asynchronous : FileOptions.None), Path.GetFileName(path), false)
> {
> }

Good to know; thanks. You aren't using either overload in SaveToFileAsync, though, which is what I was looking at when I wrote my above comment:

> using (var fs = new FileStream(filePath, fileMode))

Contributor stuff sounds good. Thanks!

**Pull request closed without merging**
